---
kind: pipeline
type: docker
name: api-conversao

steps:
  - name: npm install
    image: node:14.16.1-alpine3.13
    commands:
      - npm install
    when:
      event:
        - pull_request
        - push
  - name: npm run build
    image: node:14.16.1-alpine3.13
    commands:
      - npm run build
    when:
      event:
        - pull_request
        - push
  - name: docker build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t henrique/$(npm run version --silent) .
    when:
      event:
        - pull_request
        - push
  - name: docker push
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker push henrique/$(npm run version --silent) .
    when:
      event:
        - pull_request
        - push
