---
kind: pipeline
type: docker
name: api-conversao

steps:
  - name: npm install
    image: node:14.16.1-alpine3.13
    commands:
      - npm install
    when:
      event:
        - pull_request
        - push
  - name: npm run build
    image: node:14.16.1-alpine3.13
    commands:
      - npm run build
      - echo -n "$(npm run version --silent),latest" > .tags
    when:
      event:
        - pull_request
        - push
  - name: docker build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASSWORD
      repo: hsulimann/api-conversao
  - name: Get Kubeconfig
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER
  - name: Deploy
    image: bitnami/kubectl:latest
    commands:
      - apply -f k8s/api-conversao/
