apiVersion: v1
kind: Service
metadata:
  name: api-conversao-svc
spec:
  selector:
    app: api-conversao
  ports:
    - port: 9999
      targetPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: hsulimann/api-conversao:latest
          ports:
            - containerPort: 9999
